### PR TITLE
ASoC: wcd9xxx: use hwdep node for codec calibration

### PR DESCRIPTION
**Pull request by Rashed97**
currently codec driver uses request_firmware to get
calibration data but as this firmware file is also written by
userspace process after bootup, it is not recommended to
use request_firmware. ALSA core provides mechanism to get
hardware dependant data using hwdep nodes. Tomtom codec will
use aforementioned nodes to get calibration data from userspace.

Change-Id: Iace6e239029c7b0d93a5d61a0025ee551acf952f
Signed-off-by: Anish Kumar <kanish@codeaurora.org>

Conflicts:
	include/uapi/sound/Kbuild
	include/uapi/sound/asound.h
	sound/soc/codecs/Makefile
	sound/soc/msm/Kconfig

### CODE REVIEW

**Comment by khusika** [comment]
Thanks rashed, i'll try it. Hope it works

**Comment by khusika** [comment]
hi @Rashed97 can you help me to fix this problems?
http://pastebin.com/AsZFQmyz

**Comment by Rashed97** [comment]
Yes I can, but I'll have to go find the commit you'll need. Can you get on
IRC? Its much easier to talk there and I'm almost always on.

**Comment by khusika** [comment]
IRC? like freenode? installing now(nickname: K_TECH)
I also add your Facebook & G+ account as my friendlist

**Comment by Rashed97** [comment]
Yes freenode. My nickname is rashed so that's easy to find. Just ping me
when you have a question. If I don't answer right away, I'll answer as soon
as I see it.

**Comment by khusika** [comment]
Ok, thanks Rashed. Btw i solved this problems. I'll PM you again if get another problems :D

**Pull request merged**
